const {test}=require('node:test');
const assert=require('node:assert/strict');
const {calculate}=require('../src/saju/calculator');
const {generate}=require('../src/saju/report');
const {freeOffer}=require('../src/saju/offer');
const {paymentRequest}=require('../public/saju/payment-options');
const {testPool}=require('./helpers/saju-db');
const {createStore,token}=require('../src/saju/store');
test('free projection shows useful complete sections but omits paid payload, analysis and traces',()=>{
 const c=calculate({date:'1988-08-15',calendar:'solar',timeType:'unknown',zone:'Asia/Seoul'}),r=generate(c),original=JSON.stringify(r),f=freeOffer(r,c);
 const money=r.sections.find(s=>s.id==='money').blocks[0];
 assert.equal(f.preview.length,2);
 assert.equal(f.preview[0].title,'');
 assert.equal(f.preview[1].title,'');
 const love=r.sections.find(s=>s.id==='love').blocks[0];
 assert.ok(f.preview[1].parts[0].text.endsWith(love.parts[0].text));
 for(const part of love.parts.slice(1))assert.ok(!JSON.stringify(f).includes(part.text));
 assert.deepEqual(f.preview[0].parts,[{text:money.parts[0].text}]);
 assert.equal(f.sections,undefined);assert.equal(f.analysis,undefined);assert.equal(f.traces,undefined);
 assert.equal(f.sample,undefined);assert.equal(f.teaser,undefined);
 assert.deepEqual(f.evidence,{});assert.equal(JSON.stringify(r),original);
 for(const section of r.sections.filter(s=>s.id!=='money'))assert.ok(!JSON.stringify(f).includes(section.blocks[0].text));
 for(const part of money.parts.slice(1))assert.ok(!JSON.stringify(f).includes(part.text));
 const expanded=freeOffer(r,c,4);
 assert.equal(expanded.preview[0].parts.length,2);
 assert.ok(money.parts[1].text.startsWith(expanded.preview[0].parts[1].text));
 assert.ok(!JSON.stringify(expanded).includes(money.parts.at(-1).text));
});
test('card SDK request uses the approved hosted card window and no personal input',()=>{
 const o={id:'local_order_123',amount:4900,successUrl:'http://localhost/saju/success',failUrl:'http://localhost/saju/fail'};
 const r=paymentRequest(o,'CARD');assert.deepEqual(r.card,{flowMode:'DEFAULT'});
 assert.equal(r.amount.value,4900);assert.equal(r.windowTarget,'self');
 assert.equal(r.customerMobilePhone,undefined);assert.equal(r.customerName,undefined);
 assert.throws(()=>paymentRequest(o,'BANK'));
 assert.throws(()=>paymentRequest(o,'KAKAOPAY'));
 assert.throws(()=>paymentRequest({...o,amount:0},'CARD'));
});
test('beta entitlement stays with report while new paid reports stay locked after store restart',async t=>{
 const pool=await testPool();t.after(()=>pool.end());const secret='beta-preserve-test-'.repeat(4),store=await createStore(pool,secret),owner=token();
 const beta=await store.create({chart:{},report:{}},owner,{betaAccess:true});
 const paid=await store.create({chart:{},report:{}},owner);
 await createStore(pool,secret);
 assert.equal((await store.authorized(beta.id,owner)).beta_access,true);
 assert.equal((await store.authorized(paid.id,owner)).beta_access,false);
});
